use digital_marketing_db;
show tables;
select * from campaigns;
select * from ads;
select * from daily_performance;
-- 
-- Show all campaigns and their total revenue.
-- Even if a campaign has no ads or no performance yet.
Select 
	c.campaign_name,
	SUM(dp.revenue) AS total_revenue
From campaigns c
left join ads a
	on a.campaign_id = c.campaign_id
left join daily_performance dp
	ON dp.ad_id = a.ad_id
group by c.campaign_name;




-- Show total revenue generated by each ad along with its campaign name.
SELECT 
    c.campaign_name,
    a.ad_name,
    SUM(dp.revenue) AS total_revenue
FROM daily_performance dp
JOIN ads a 
    ON a.ad_id = dp.ad_id
JOIN campaigns c
    ON c.campaign_id = a.campaign_id
GROUP BY c.campaign_name, a.ad_name
ORDER BY total_revenue DESC;



--  Show each ad with its campaign name and channel.
select 
	a.ad_name as `Ad Name`, 
	c.campaign_name as `Campaign Name`,
	c.channel as `Channel`
from ads a
left join campaigns c
	on c.campaign_id = a.campaign_id