-- What is the total impressions, total clicks, total conversions and total revenue for each campaign?
-- Show total revenue per channel
select cam.channel, 
sum(dp.revenue) as Revenue, 
sum(impressions) as Impressions,
sum(clicks) as clicks,
sum(conversions) as conversion 
from daily_performance as dp
join ads 
on ads.ad_id = dp.ad_id
join campaigns cam
on cam.campaign_id = ads.campaign_id
group by cam.channel;

-- -----------------------
-- Which campaign has the highest ROAS?
-- Reminder: ROAS = Revenue / Spend

-- Write a query that:
-- Shows campaign_name
-- Total revenue
-- Total spend
-- ROAS
-- Orders by ROAS descending
-- Answer
SELECT 
    c.campaign_name,
    SUM(dp.revenue) AS total_revenue,
    SUM(dp.spend) AS total_spend,
    ROUND(
        SUM(dp.revenue) / NULLIF(SUM(dp.spend), 0), 2
    ) AS ROAS
FROM daily_performance dp
JOIN ads a 
    ON a.ad_id = dp.ad_id
JOIN campaigns c 
    ON c.campaign_id = a.campaign_id
GROUP BY c.campaign_name
ORDER BY ROAS DESC;
-- 

-- Practice with Join and Solve Business Questions
--  Show each ad with its campaign name and channel.
select 
	a.ad_name as `Ad Name`, 
	c.campaign_name as `Campaign Name`,
	c.channel as `Channel`
from ads a
left join campaigns c
	on c.campaign_id = a.campaign_id

-- --------------------
-- Show total revenue generated by each ad along with its campaign name.
SELECT 
    c.campaign_name,
    a.ad_name,
    SUM(dp.revenue) AS total_revenue
FROM daily_performance dp
JOIN ads a 
    ON a.ad_id = dp.ad_id
JOIN campaigns c
    ON c.campaign_id = a.campaign_id
GROUP BY c.campaign_name, a.ad_name
ORDER BY total_revenue DESC;

--  Show each ad with its campaign name and channel.
select 
	a.ad_name as `Ad Name`, 
	c.campaign_name as `Campaign Name`,
	c.channel as `Channel`
from ads a
left join campaigns c
	on c.campaign_id = a.campaign_id

-- Show all campaigns and their total revenue.
-- Even if a campaign has no ads or no performance yet.

 SELECT 
    c.campaign_name,
    COALESCE(SUM(dp.revenue), 0) AS total_revenue
FROM campaigns c
LEFT JOIN ads a
    ON c.campaign_id = a.campaign_id
LEFT JOIN daily_performance dp
    ON a.ad_id = dp.ad_id
GROUP BY c.campaign_name;
